'use strict';

const fs = require('fs');
const path = require('path');
const { run } = require('./connection');

async function initSchema() {
  // 마이그레이션: update_log가 INTEGER PRIMARY KEY (구)로 있으면 DROP
  // 새 스키마는 GENERATED BY DEFAULT AS IDENTITY (DuckDB 표준 AUTO_INCREMENT)
  try {
    const check = await run(`SELECT column_name, data_type, is_identity FROM information_schema.columns WHERE table_name = 'update_log' AND column_name = 'id'`);
    // row가 있으면 column 정보 있음
  } catch (e) { /* 테이블 없으면 무시 */ }
  // DuckDB는 is_identity 확인이 복잡하므로, 안전하게 update_log가 있으면 DROP
  // (로그 테이블은 매일 갱신되는 임시 데이터라 데이터 손실 무시)
  try {
    const r = await run(`SELECT id FROM update_log LIMIT 1`);
    // id가 BIGINT면 구 스키마 (INTEGER PRIMARY KEY만으론 AUTO_INCREMENT 안 됨)
    // 일단 DROP하고 재생성 (마이그레이션 안전)
    if (r) {
      await run(`DROP TABLE IF EXISTS update_log`);
    }
  } catch (e) {
    // 테이블 없으면 OK
  }

  const sql = fs.readFileSync(path.join(__dirname, 'schema.sql'), 'utf8');
  // DuckDB는 여러 statement를 한 번에 실행 가능하지만 안전하게 split
  const stmts = sql
    .split(/;\s*$/m)
    .map((s) => s.trim())
    .filter(Boolean);
  for (const s of stmts) {
    await run(s);
  }
}

module.exports = { initSchema };
