'use strict';

const fs = require('fs');
const path = require('path');
const { run } = require('./connection');

async function initSchema() {
  // 마이그레이션: update_log가 INTEGER PRIMARY KEY (구)로 있으면 DROP
  // 새 스키마는 GENERATED BY DEFAULT AS IDENTITY (DuckDB 표준 AUTO_INCREMENT)
  const { one } = require('./connection');
  try {
    const r = await one(`SELECT id FROM update_log LIMIT 1`);
    if (r) {
      // row 있음 → 구 스키마 또는 정상
      // AUTO_INCREMENT 작동 확인 (id 없이 INSERT 가능한지)
      try {
        // 임시 시도: 트랜잭션 내에서 rollback
        // (단순화: 그냥 DROP하고 재생성)
      } catch (_) { /* 무시 */ }
    }
  } catch (e) {
    // 테이블 없으면 OK
  }
  // DuckDB AUTO_INCREMENT 확인이 복잡하므로 안전하게 DROP 후 재생성
  // (update_log는 매일 갱신, 누적 가치 없음)
  try {
    await run(`DROP TABLE IF EXISTS update_log`);
  } catch (e) { /* ignore */ }

  const sql = fs.readFileSync(path.join(__dirname, 'schema.sql'), 'utf8');
  // DuckDB는 여러 statement를 한 번에 실행 가능하지만 안전하게 split
  const stmts = sql
    .split(/;\s*$/m)
    .map((s) => s.trim())
    .filter(Boolean);
  for (const s of stmts) {
    await run(s);
  }
}

module.exports = { initSchema };
